Fix sanity check error for FAN_PIN / SPEAKER timer conflict
New sanity check error reported due the TIMER2 conflict.
Marlin\src\HAL\AVR\../../inc/../HAL/AVR/inc/SanityCheck.h:39:4: error: 
#error "FAN_PIN 9 Hardware PWM uses Timer 2 which conflicts with Arduino AVR Tone Timer (for SPEAKER)."
#error "Disable SPEAKER or enable FAN_SOFT_PWM."