Update Configuration.h
Remove X_MIN_PIN, X_MAX_PIN,Y_MIN_PIN Y_MAX_PIN pin definitions  and comment out `#define REPRAP_DISCOUNT_SMART_CONTROLLER` since they break compilation for Polar.

Error message:
```
/Users/drf/Work/Marlin/Marlin/src/lcd/marlinui.cpp: In static member function 'static void ManualMove::task()':
/Users/drf/Work/Marlin/Marlin/src/lcd/marlinui.cpp:774:60: error: 'manual_feedrate_mm_s' was not declared in this scope
         const feedRate_t fr_mm_s = (axis < LOGICAL_AXES) ? manual_feedrate_mm_s[axis] : XY_PROBE_FEEDRATE_MM_S;
                                                            ^~~~~~~~~~~~~~~~~~~~
/Users/drf/Work/Marlin/Marlin/src/lcd/marlinui.cpp:774:60: note: suggested alternative: 'feedrate_mm_s'
         const feedRate_t fr_mm_s = (axis < LOGICAL_AXES) ? manual_feedrate_mm_s[axis] : XY_PROBE_FEEDRATE_MM_S;
                                                            ^~~~~~~~~~~~~~~~~~~~
                                                            feedrate_mm_s
```

`manual_feedrate_mm_s` is defined in src/module/planner.h at https://github.com/MarlinFirmware/Marlin/blob/2.0.x/Marlin/src/module/planner.h#L84  and doesn't seem to work with a 3-axis POLARGRAPH with with either a 3-axis or 4-axis MANUAL_FEEDRATE defined in Configuration_adv.h.